
---
sudo: false
language: rust
rust:
  - stable
  - nightly
  - beta

matrix:
  allow_failures:
    - rust: stable
    - rust: beta

os:
  - linux
  - osx

branches:
  only:
    - master

env:
  - ARCH=x86_64
  - ARCH=i686

script:
  - cargo build
  - cargo test

addons:
  apt:
    packages:
      - gcc-multilib
